"""initial migration

Revision ID: 5afed03595fd
Revises: 
Create Date: 2025-06-22 18:05:18.901030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5afed03595fd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('restaurant_pizzas_pizza_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('restaurant_pizzas_restaurant_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pizzas', ['pizza_id'], ['id'])
        batch_op.create_foreign_key(None, 'restaurants', ['restaurant_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurant_pizzas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('restaurant_pizzas_restaurant_id_fkey'), 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('restaurant_pizzas_pizza_id_fkey'), 'pizzas', ['pizza_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
